export const TEST_DISPATCH = 'TEST_DISPATCH';
export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_EMPLOYEE_RECORD = 'SET_EMPLOYEE_RECORD';
export const GET_ALL_EMPLOYEE_RECORD = 'GET_ALL_EMPLOYEE_RECORD';